name: Deploy Staging to GitHub Pages

on:
  push:
    branches:
      - openaccesslocal  # Trigger this on pushes to the staging branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build for Staging
        run: npm run build -- --mode staging

      - name: Deploy to GitHub Pages (Staging)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: staging  # Deploy to /staging
          user_name: BlacIP
          user_email: blacip@users.noreply.github.com