name: Deploy Staging to GitHub Pages

on:
  push:
    branches: [ openaccesslocal ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Ensure Vite builds with the correct base
      - name: Build for Staging
        run: npm run build -- --mode staging

      - name: Add SPA fallback for GitHub Pages
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages (Staging)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          destination_dir: staging         # serves at /staging
          keep_files: true                 # keep production files at root
          enable_jekyll: false