name: Deploy Production to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Force Vite base to root for the custom domain
      - name: Set Vite base for custom domain
        run: echo "VITE_APP_BASE=/" >> $GITHUB_ENV

      - name: Build for Production
        run: npm run build -- --mode production
        
      - name: Add SPA fallback for GitHub Pages
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages (Production)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          cname: openaccessconsult.com     # writes CNAME at branch root
          keep_files: true                 # keep /staging intact
          enable_jekyll: false